item {
  id: 1
  display_name: "Ag-P"
}
item {
  id: 2
  display_name: "Ag-T"
}
item {
  id: 3
  display_name: "Ag-U"
}
item {
  id: 4
  display_name: "Cu-P"
}
item {
  id: 5
  display_name: "Cu-T"
}
item {
  id: 6
  display_name: "Cu-U"
}
item {
  id: 7
  display_name: "Pb-P"
}
item {
  id: 8
  display_name: "Pb-T"
}
item {
  id: 9
  display_name: "Pb-U"
}
